---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
 name: cloudwatchmetricalarms.ccp.swacorp.com
spec:
 group: ccp.swacorp.com
 version: v1
 versions:
   - name: v1
     served: true
     storage: true
 scope: Namespaced
 names:
   kind: cloudwatchmetricalarm
   plural: cloudwatchmetricalarms
   singular: cloudwatchmetricalarm
   shortNames:
     - cwma
     - cwmas
 preserveUnknownFields: true
 
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
 name: cloudwatchcompositalarms.ccp.swacorp.com
spec:
 group: ccp.swacorp.com
 version: v1
 versions:
   - name: v1
     served: true
     storage: true
 scope: Namespaced
 names:
   kind: cloudwatchcompositalarm
   plural: cloudwatchcompositalarms
   singular: cloudwatchcompositalarm
   shortNames:
     - cwca
     - cwcas
 preserveUnknownFields: true
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: cloudwatchalarm-controller-role
 labels:
   app.kubernetes.io/component: controller
   app.kubernetes.io/name: cloudwatchalarm-controller
rules:
- apiGroups:
 - ccp.swacorp.com
 resources:
 - cloudwatchcompositalarms
 - cloudwatchmetricalarms
 verbs:
 - '*'
- apiGroups: [apiextensions.k8s.io]
 resources: [customresourcedefinitions]
 verbs: [list, watch]
- apiGroups: [""]
 resources: [namespaces]
 verbs: [list, watch]
- apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
 resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
 verbs: [create, patch]
- apiGroups: [""]
 resources: [events]
 verbs: [create, patch, list, watch, delete]
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cloudwatchalarm-controller-rolebinding
 labels:
   app.kubernetes.io/component: controller
   app.kubernetes.io/name: cloudwatchalarm-controller
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cloudwatchalarm-controller-role
subjects:
- kind: ServiceAccount
 name: cloudwatchalarm-controller
 namespace: kube-system
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: cloudwatchalarm-controller
 namespace: kube-system
 labels:
   app: cloudwatchalarm
spec:
 replicas: 1
 strategy:
   type: Recreate
 selector:
   matchLabels:
     app: cloudwatchalarm
     role: operator
 template:
   metadata:
     labels:
       app: cloudwatchalarm
       role: operator
     annotations:
       prometheus.io/scrape: 'false'
   spec:
     serviceAccountName: cloudwatchalarm-controller
     containers:
       - name: cloudwatchalarm
         image: {{IMAGE PUSHED FROM STEP ABOVE}}
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
             name: http
             protocol: TCP
         resources:
           requests:
             cpu: "100m"
             memory: "256Mi"
           limits:
             cpu: "500m"
             memory: "500Mi"
 
---
apiVersion: v1
kind: Service
metadata:
 name: cloudwatchalarm-svc
 namespace: kube-system
spec:
 sessionAffinity: None
 type: ClusterIP
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: cloudwatchalarm
   role: operator
