
---
apiVersion: cw.aws.com/v1
kind: cloudwatchmetricalarm
metadata:
  namespace: kube-system
  name: test-kube-dns-alarm
spec:
  EvaluationPeriods: 4
  DatapointsToAlarm: 2
  ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
  ThresholdMetricId: ad1
  AlarmActions:
    - {{ ARN_FOR_ACTION_RESOURCE }}
  Metrics:
    - Id: "m1"
      ReturnData: true
      MetricStat:
        Metric:
          Namespace: ContainerInsights
          MetricName: pod_cpu_utilization
          Dimensions:
            - Name: ClusterName
              Value: {{CLUSTER_NAME}}
            - Name: Serivce
              Value: kube-dns
            - Name: Namespace
              Value: kube-system
        Period: 10
        Stat: p95
    - Id: ad1
      Label: pod_cpu_utilization (expected)
      ReturnData: true
      Expression: ANOMALY_DETECTION_BAND(m1, 2)

---
apiVersion: cw.aws.com/v1
kind: cloudwatchmetricalarm
metadata:
  namespace: kube-system
  name: test-cluster-autoscaler-alarm
spec:
  EvaluationPeriods: 4
  DatapointsToAlarm: 2
  ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
  ThresholdMetricId: ad1
  AlarmActions:
    - {{ ARN_FOR_ACTION_RESOURCE }}
  Metrics:
    - Id: "m1"
      ReturnData: true
      MetricStat:
        Metric:
          Namespace: ContainerInsights
          MetricName: pod_cpu_utilization
          Dimensions:
            - Name: ClusterName
              Value: {{CLUSTER_NAME}}
            - Name: Serivce
              Value: cluster-autoscaler
            - Name: Namespace
              Value: cluster-autoscaler
        Period: 10
        Stat: p95
    - Id: ad1
      Label: pod_cpu_utilization (expected)
      ReturnData: true
      Expression: ANOMALY_DETECTION_BAND(m1, 2)

---
apiVersion: cw.aws.com/v1
kind: cloudwatchcompositalarm
metadata:
  namespace: kube-system
  name: test-composit-alarm
spec:
  AlarmRule: ALARM("kube-system-test-cluster-autoscaler-alarm") OR ALARM("kube-system-test-kube-dns-alarm")